- name: Dynamically add master and worker to inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add master to inventory
      add_host:
        name: "{{ master_node }}"
        groups: master_node

    - name: Add new worker to inventory
      add_host:
        name: "{{ new_vm_ip }}"
        groups: new_vm_ip

    - name: Retrieve RKE2 token from master node
      ansible.builtin.slurp:
        src: /var/lib/rancher/rke2/server/node-token
      register: rke2_token_raw
      delegate_to: "{{ master_node }}"

    - name: Set rke2_token fact globally
      delegate_to: localhost
      set_fact:
        rke2_token: "{{ rke2_token_raw.content | b64decode | trim }}"

    - name: Create /etc/rancher/rke2 on worker nodes
      ansible.builtin.file:
        path: /etc/rancher/rke2
        state: directory
        mode: '0755'
        recurse: true
      delegate_to: "{{ new_vm_ip }}"

    - name: Copy RKE2 config for workers
      template:
        src: rke2-config-worker.yaml.j2
        dest: /etc/rancher/rke2/config.yaml
        mode: '0644'
      delegate_to: "{{ new_vm_ip }}"

    - name: Permanently add RKE2 to PATH in root's .bashrc
      become: yes
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        line: 'export PATH=$PATH:/var/lib/rancher/rke2/bin'
        state: present
      delegate_to: "{{ new_vm_ip }}"
    
    - name: Permanently add crictl to PATH in global bashrc
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/bashrc
        line: 'export CONTAINER_RUNTIME_ENDPOINT=unix:///run/k3s/containerd/containerd.sock'
        state: present
      delegate_to: "{{ new_vm_ip }}"
    
    - name: Restart rke2-agent
      systemd:
        name: rke2-agent
        state: restarted
        enabled: true
      delegate_to: "{{ new_vm_ip }}"
